# Generated by Django 5.1.4 on 2025-01-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('map_url', models.CharField(max_length=500)),
                ('img_url', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=250)),
                ('has_sockets', models.BooleanField()),
                ('has_toilet', models.BooleanField()),
                ('has_wifi', models.BooleanField()),
                ('can_take_calls', models.BooleanField()),
                ('seats', models.CharField(blank=True, max_length=200, null=True)),
                ('coffee_price', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cafe',
                'managed': False,
            },
        ),
    ]
